class PaperSubtopic < ApplicationRecord
  belongs_to :paper_topic

  def to_s
    if I18n.locale == :en
      english_name
    else
      name
    end
  end

  private

  def english_name
    case name
    when 'Espacios innovadores para el aprendizaje'
      'Innovative learning spaces'
    when 'Aula Invertida'
      'Inverted classroom'
    when 'Gamificación'
      'Gamification'
    when 'Aprendizaje basado en competencias'
      'Competency-based learning'
    when 'Aprendizaje Híbrido'
      'Hybrid learning'
    when 'Aprendizaje flexible y personalizado'
      'Flexible and personalized learning'
    when 'Aprendizaje Vivencial'
      'Experiential learning'
    when 'Aprendizaje Activo'
      'Active learning'
    when 'Aprendizaje basado en retos'
      'Challenge-based learning'
    when 'Conectivismo y aprendizaje social'
      'Connectivism and social learning'
    when 'Evaluación constructiva del aprendizaje'
      'Constructive evaluation of learning'
    when 'El nuevo Curriculum'
      'The new curriculum'
    when 'Acceso abierto (Prácticas, recursos, repositorios)'
      'Open access (practices, resources, repositories)'
    when 'Aprendizaje Móvil'
      'Mobile learning'
    when 'Multidisciplinariedad'
      'Multidisciplinarity'
    when 'Movimiento /"makers"/'
      'Makers movement'
    when 'Otro'
      'Other'
    when 'Aprendizaje adaptivo'
      'Adaptive learning'
    when 'Aprendizaje obicuo'
      'Ubiquitous learning'
    when 'Realidad Virtual'
      'Virtual reality'
    when 'Realidad Aumentada'
      'Augmented reality'
    when "Mooc's"
      "Mooc's"
    when 'Analíticas de Aprendizaje'
      'Learning analytics'
    when 'Tecnologías Visibles'
      'Visible technologies'
    when 'Tecnologías Emergentes'
      'Emerging technologies'
    when 'Redes sociales de colaboración'
      'Social networks of collaboration'
    when 'Aprendizaje Móvil'
      'Mobile learning'
    when 'BYOD'
      'BYOD'
    when 'Otro'
      'Other'
    when 'Competencias y habilidades requeridas en el futuro'
      'Skills and habilities required for the future'
    when 'Nuevas tendencias y modelos de formación para toda la vida'
      'New trends and lifelong training models '
    when 'Impacto de nuevas tecnologías en la educación contínua'
      'Impact of new technologies in continuous education'
    when 'Credenciales alternativas'
      'Alternative credentials'
    when 'Colaboración Industria/Universidad'
      'Industry-University collaboration'
    when 'Autoaprendizaje'
      'Self learning'
    when 'Implicaciones de la generación digital en la educación a lo largo de la vida'
      'Digital generation implications in lifelong education'
    when 'Indicadores de Innovación Educativa'
      'Education innovaction indicators'
    when 'Nuevos Modelos de Instituciones Educativas'
      'New models of education institutions'
    when 'Transformación de procesos'
      'Process transformation'
    when 'Modelos de capacitación y desarrollo'
      'Training and development models'
    when 'Metodologías para la innovación'
      'Innovation methodologies'
    when 'Procesos de innovación en las instituciones'
      'Innovation processes in institutions'
    when 'Retos de camnio y la complejidad actual'
      'Change challenges and current complexity'
    when 'Internaciolización'
      'Internationalization'
    when 'Derechos de autor y propiedad intelectual'
      'Copyright and intellectual property'
    when 'Recursos para la innovación'
      'Innovation resources'
    when 'Procesos para trabajar adicciones digitales y su prevención'
      'Processes to treat digital addictions and prevention'
    when 'Resiliencia Personal/Académica'
      'Personal/academic resilience'
    when 'Abordaje del bullying y Cyberbullying'
      'Bullying and Cyberbullying approaches'
    when 'Modelos de tutoría'
      'Tutoring models'
    when 'Otro'
      'Other'
    when 'Aprendizaje médico interdisciplinario'
      'Interdisciplinary medical learning'
    when 'Humanismo en medicina'
      'Humanism in medicine'
    when 'Tecnología en educación médica'
      'Technology in medical education'
    when 'Aprendizaje centrado en los pacientes'
      'Patient centered learning'
    when 'Otros (Casos clínicos, herramientas para el desarrollo del juicio médico)'
      'Other'
    when 'Inversión y financiamiento'
      'Investment and finance'
    when 'Desarrollo de soluciones'
      'Development of solutions'
    when 'Liderazgo de equipos'
      'Team leadership'
    when 'Validación y prototipos'
      'Prototyping and validation'
    when 'Marketing y estrategia'
      'Marketing and strategy'
    when 'Programas para emprendedores'
      'Entrepreneurship programs'
    when 'Otro'
      'Other'
    else
      name
    end
  end
end
